stages:
  data_extraction:
    cmd: python src/stages/extraction.py --config params.yaml
    deps:
      - src/stages/extraction.py
    params:
      - extraction
  data_concatenation:
    cmd: python src/stages/concatenation.py --config params.yaml
    deps:
      - src/stages/concatenation.py
    outs:
      - data/raw/car_raw.csv
    params:
      - concatenation
  feature_engineering:
    cmd: python src/stages/feature_engineering.py --config params.yaml
    deps:
    - data/raw/car_raw.csv
    outs:
    - models/feature_engineering_pipeline.joblib

  train:
    cmd: python src/stages/train.py --config params.yaml
    deps:
    - src/stages/train.py
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - models/feature_engineering_pipeline.joblib
    outs:
    - models/final_pipeline.joblib
  # evaluate:
  #   cmd: python src/stages/evaluate.py --config params.yaml
  #   deps:
  #     - src/stages/evaluate.py
  #     - data/processed/X_transformed.csv
  #   metrics:
  #     - reports/metrics.json:
  #         cache: false
  #   plots:
  #     - reports/clusters.png:
  #         cache: false